spring.application.name=demo

server.port=8080

# Conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/lab02
spring.datasource.username=postgres
spring.datasource.password=1357924680
spring.datasource.driver-class-name=org.postgresql.Driver

# Fallback para que la app no explote si no hay DB
spring.datasource.continue-on-error=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

spring.data.rest.detection-strategy=annotated

# JWT (HS256): la clave debe tener al menos 32 caracteres
jwt.secret=eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikp
jwt.expiration-ms=86400000

# Google Maps API Configuration
# Reemplace con una API Key válida con permisos de 'Geocoding API'
google.maps.api.key=AIzaSyByQkOq_Gk7Ue0F27CuoiffA9hnZhLCsfY